import FirebaseAILogic
import Foundation

/// The response from a content generation request.
@available(iOS 15.0, macOS 12.0, macCatalyst 15.0, tvOS 15.0, watchOS 8.0, *)
@objc(KFBGenerateContentResponse)
public final class GenerateContentResponse: NSObject, @unchecked Sendable {
    let value: FirebaseAILogic.GenerateContentResponse

    init(value: FirebaseAILogic.GenerateContentResponse) {
        self.value = value
        super.init()
    }

    /// The list of response candidates generated by the model.
    @objc public var candidates: [Candidate] {
        value.candidates.map { Candidate(value: $0) }
    }

    /// Feedback about the prompt, including safety filtering results.
    @objc public var promptFeedback: PromptFeedback? {
        value.promptFeedback.map { PromptFeedback(value: $0) }
    }

    /// Token usage metadata for the request and response.
    @objc public var usageMetadata: UsageMetadata? {
        value.usageMetadata.map { UsageMetadata(value: $0) }
    }

    /// The concatenated text from the first candidate, or `nil` if unavailable.
    @objc public var text: String? {
        value.text
    }

    /// A summary of the model's thinking process, or `nil` if unavailable.
    @objc public var thoughtSummary: String? {
        value.thoughtSummary
    }

    /// The function calls returned by the model, if any.
    @objc public var functionCalls: [FunctionCallPart] {
        value.functionCalls.map { FunctionCallPart(value: $0) }
    }

    /// The inline data parts (e.g., images) returned by the model, if any.
    @objc public var inlineDataParts: [InlineDataPart] {
        value.inlineDataParts.map { InlineDataPart(value: $0) }
    }
}
