import FirebaseAILogic
import Foundation

/// Content received from the server during a live session.
@available(iOS 15.0, macOS 12.0, macCatalyst 15.0, tvOS 15.0, watchOS 8.0, *)
@available(watchOS, unavailable)
@objc(KFBLiveServerContent)
public final class LiveServerContent: NSObject, @unchecked Sendable {
    let value: FirebaseAILogic.LiveServerContent

    init(value: FirebaseAILogic.LiveServerContent) {
        self.value = value
        super.init()
    }

    /// The content generated by the model for this turn, if available.
    @objc public var modelTurn: ModelContent? {
        return value.modelTurn.map { ModelContent(value: $0) }
    }

    /// Whether the model's turn is complete.
    @objc public var isTurnComplete: Bool {
        return value.isTurnComplete
    }

    /// Whether the model's response was interrupted.
    @objc public var wasInterrupted: Bool {
        return value.wasInterrupted
    }

    /// Whether content generation is complete.
    @objc public var isGenerationComplete: Bool {
        return value.isGenerationComplete
    }

    /// The transcription of the input audio, if available.
    @objc public var inputAudioTranscription: LiveAudioTranscription? {
        return value.inputAudioTranscription.map { LiveAudioTranscription(value: $0) }
    }

    /// The transcription of the output audio, if available.
    @objc public var outputAudioTranscription: LiveAudioTranscription? {
        return value.outputAudioTranscription.map { LiveAudioTranscription(value: $0) }
    }
}
